server:
  port: 9096
  servlet:
    context-path: /

spring:
  application:
    name: cooptec-activiti-server
  profiles:
    active: dev
  resources:
    chain:
      cache: false
  freemarker:
    content-type: text/html;charset=utf-8
    request-context-attribute: ctx
    settings:
      locale: zh_CN
      template_update_delay: 0
      defaultEncoding: UTF-8
      url_escaping_charset: UTF-8
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss
      number_format: #.##
      whitespace_stripping: true
  activiti:
    check-process-definitions: false
    database-schema-update: true
    history-level: full
    db-history-used: true

mybatis:
  config-location: "classpath:/mybatis/mybatis-config.xml"
  mapper-locations: "classpath:/mybatis/mappers/**/*.xml"
